### ISSUE TITLE
Breaking the last block of a stage doesn't update all party members to subsequent stage. 

### ISSUE THREAD

**Issue by louisspaghetti** [PikaMug/Quests#1172]
Quest Version: 3.9.0-b83
Parties Version: 2.6.14

Error log after breaking the last block of the stage:
https://pastebin.com/1W504diw
Complete error log:
https://pastebin.com/Xj1Y7wPZ

At the end of a stage that involved breaking 10 cobwebs, the last cobweb broke gave the above error log. Only the person who broke the cobweb had the block break counted and moved onto the next stage while the other players in the party stayed at 9 cobwebs and didn't advance to the next stage

quests.yml file:
https://pastebin.com/S6JrJ2dM

**Comment by louisspaghetti** [comment]
So how do I incorporate this commit into the plugin? Do I have the wait for the latest build to update or build it myself? Or, is there anything I can change about my data atm to get it working with the current build I have?

**Comment by PikaMug** [comment]
@louisspaghetti https://ci.codemc.io/job/PikaMug/job/Quests/90/

**Comment by louisspaghetti** [comment]
@PikaMug Thanks! Really really helpful!

**Comment by louisspaghetti** [comment]
I downloaded the newest plugin and the error log stopped appearing (it had also stopped in the previous build I was using) but my previous issue still remains. The party members get desynced at the end of the stage. 

This time, however, the first stage which includes breaking blocks keeps the members synced but the following breaking block stage has them desynced after the last block is place. This issue also occurs on the last (third) stage which includes placing blocks rather than breaking them.

I feel like this issue should be reopened since the original bug hasn't been fixed, only the errors stopped appearing? Please, if there are any other config files I can provide, just mention them and I'll be happy to send them over!

**Comment by PikaMug** [comment]
@louisspaghetti I would not mind re-opening if you would edit your original post to link to a quests.yml file on Pastebin. Currently, it only links to a short description of the problem.

**Comment by louisspaghetti** [comment]
@PikaMug My mistake! I must've selected the wrong text when copy/pasting so I fixed it now. Again, I'm glad to provide any files since this isn't a commercial server or anything like that, just a personal one between friends.

**Comment by PikaMug** [comment]
@louisspaghetti Does the issue still occur if you turn `require-same-quest` off?

**Comment by louisspaghetti** [comment]
@PikaMug No, the issue is solved by turning this property to false! The only difference I can tell after turning off the feature (which I have no idea it's used for), is that this issue is fixed, nothing else changes which makes me think it was completely broken with my config?

**Comment by PikaMug** [comment]
The purpose of that flag is to force players to work on the same quest. If for example, you made a second quest about breaking Cobweb, having `require-same-quest: true` would prevent some party members working on the first quest from contributing to other members working on the second.

However, it seems this feature isn't working correctly. Looking into a solution now.

**Comment by PikaMug** [comment]
@louisspaghetti Fairly certain https://ci.codemc.io/job/PikaMug/job/Quests/91/ will fix the issue, but I'd appreciate if you'd give it a try with `require-same-quest` enabled. Either way, thanks for using Quests.
