### ISSUE TITLE
Format Codes Bug

### ISSUE THREAD

**Issue by Drizzt11** [PikaMug/Quests#2321]
### What is your Quests version / build number (do *not* say "latest")?

5.1.6

### Describe the problem and how to replicate it.

When an npc is named with format codes they show up in the quests text and giu

### Any console errors to share?

```shell
No console error to report
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
'000001':
    name: Introductions - West Side Windria
    ask-message: '[Quest] - Welcome Newcomer! Here report to these citizens in West
      Side Windria. They all have tasks and jobs needing to be done. After you finish
      report back to me. **Rewards: $900 9QP 225XP**'
    finish-message: §9[§6§lQuests§9] - §2Quest Completed§9!
    npc-giver-uuid: 7a85fa6e-75e3-4565-a74a-a0fb8ed6dbbd
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 4082
      type: PAPER
    stages:
      ordered:
        '1':
          npc-uuids-to-talk-to:
          - c7c5e3a3-ae80-4d51-a170-eeb2a72a87ab
          - 2dc1ee6d-5750-4303-8ff8-eaaa21cfa609
          - 2aed2a1c-e50a-4c24-a4bb-f1a3dd3935d0
          - d201daf4-402f-48eb-bed2-c9e051e5a34c
          - 51af3f21-6dd7-4931-9bf6-1012ecea3919
          - ec60cc1b-7803-445a-a7b6-c46fe0458659
          - 631543ae-4c35-4d1c-abce-bb633d8cd0ab
          - 3b5bfe26-3814-46ef-9d1b-9e022d45c6d6
          - 47ccc013-acd9-49c6-a738-0c6d0e327840
          start-message: '17'
          complete-message: '&9[&6&lQuests&9] - &cQuest Objective Completed&9!'
        '2':
          npc-uuids-to-talk-to:
          - 7a85fa6e-75e3-4565-a74a-a0fb8ed6dbbd
          start-message: '&9[&6&lQuests&9] - &9Now that is done, report to the &6Receptionist&9
            at the &cWindria Town Hall&9.'
          complete-message: '&9[&6&lQuests&9] - &cQuest Objective Completed&9!'
    rewards:
      money: 800
      quest-points: 8
      exp: 200
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```

**Comment by PikaMug** [comment]
Should be fixed in 7099106e9c1e7d4f82ea53e890a83b87fd09fb2a

Please try https://ci.codemc.io/job/PikaMug/job/Quests/517/

**Comment by Drizzt11** [comment]
So still the same shows up in quest journal as <gold><b>NPC-Name and still
shows up as <b>NPCName when you pickup the quest. if you want I can show
you a picture

**Comment by PikaMug** [comment]
@Drizzt11 Try https://ci.codemc.io/job/PikaMug/job/Quests/518/ and if there are any other issues, pictures would be helpful

**Comment by Drizzt11** [comment]
Quest Gui and Quest Editor shows the format codes but the text for the npc
when accepting a quest works great no format codes so that parts fixed here
are a few pictures

**Comment by PikaMug** [comment]
@Drizzt11 It seems your pictures did not transfer. Also, please note this repo is for Quests; not QuestsGUI.

**Comment by PikaMug** [comment]
Try https://ci.codemc.io/job/PikaMug/job/Quests/519/

**Comment by Drizzt11** [comment]
Looks like you dont need my pictures lol. You fixed it all. Everything is
displaying the names correctly including QuestsGUI. Thank you so much!
