### ISSUE TITLE
Block Break Stage disappears on server restart

### ISSUE THREAD

**Issue by Nericu** [PikaMug/Quests#793]
**3.6.6, 3.6.7, 3.6.8dev**

**If a player is on a quest stage that requires them to break a certain amount of blocks (100 dirt blocks) then on a server reset if they are in teh process of completing it (50/100 dirt blocks) then the quest completely loses its stages and the player has to quit the quest and restart it**

Screenshot of how the quest shows up in the Quest Journal after a restart.
![2019-05-13_21 22 12](https://user-images.githubusercontent.com/6724427/57664202-36359880-75c5-11e9-9b96-0f42ec47d912.png)

**Comment by PikaMug** [comment]
Possibly related to #772

**Comment by PikaMug** [comment]
@Nericu Please check if http://ci.ac3-servers.eu/job/Quests/742/ resolves the issue.

**Comment by Nericu** [comment]
Seems to still be happening, on a side note (prob should be another issue) it seems teh quests.yml file cannot be read if using spigot 1.14.1 btw...had to revert to 1.14 just to get our quests back and it even erased all the player data so I had to give everyone their quests back and stuff.

**Comment by PikaMug** [comment]
@Nericu I'll keep looking into this then. Thanks!

Definitely create another ticket for the 1.14.1 issue, if you can.

**Comment by Nericu** [comment]
Ok only prob is I dont have a ton of information on it but I will do what I can

**Comment by PikaMug** [comment]
Since the Jenkins server is down, try this build and let me know the results:
https://www.dropbox.com/s/vlu1dd2v0hxibrh/Quests-3.7.1.jar?dl=0

**Comment by Nericu** [comment]
> Since the Jenkins server is down, try this build and let me know the results:
> https://www.dropbox.com/s/vlu1dd2v0hxibrh/Quests-3.7.1.jar?dl=0

I will try it when I get done work today and get back to you on it. Thanks

**Comment by Nericu** [comment]
Ok that build didn't resolve the issue, in fact this build removed all quests from everyone each startup. The quests were there to get but if the server restarted everyone lost all quests and progress on them...

**Comment by PikaMug** [comment]
Alright, sorry for the inconvenience. I hope to find a proper solution soon.

**Comment by PikaMug** [comment]
@Nericu I’m having trouble replicating this on Quests 3.7.7. Is this still happening for you?

**Comment by 18PatZ** [comment]
Hey @Nericu, I can't seem to replicate the issue either. We're thinking it may have been fixed accidentally already.

**Comment by Nericu** [comment]
Sounds good, I will update if I am still having trouble but wont be able to really test until tomorrow.

**Comment by Nericu** [comment]
Yeah looks like I am still having this issue. I honestly have no idea what it could be other then McMMO Overhaul because that is the only thing that effects woodcutting on our server but I cant see that resetting the entire quest....

**Comment by 18PatZ** [comment]
@Nericu could you send your config and maybe a video of it happening?

**Comment by Nericu** [comment]
https://clips.twitch.tv/CaringSilkyGiraffeTTours thats a clip of it happening. It seems all you have to do now is just leave/join the server for it to reset as well, before it was just upon restarts that it messed it up.

Quests.yml - https://pastebin.com/Q96wDw9G
Config.yml - https://pastebin.com/dEPnKwK3

**Comment by PikaMug** [comment]
I was able to replicate this using your quest. The problem only arises when the block break objective is the Stage 2 of the quest. Using the objective for Stage 1 works as expected.

For anyone else testing this, here's the same quest which I've stripped of unnecessary fields:
https://pastebin.com/cemhSCmk

Code-wise, I'm seeing the [blocksBroken](https://github.com/PikaMug/Quests/blob/master/main/src/main/java/me/blackvein/quests/QuestData.java#L84) list doesn't appear to be populated after re-logging, which in turn causes [a loop in showObjectives](https://github.com/PikaMug/Quests/blob/master/main/src/main/java/me/blackvein/quests/Quests.java#L674) to go untriggered.

Unfortunately, that's all the time I have for now. Will investigate further soon.

**Comment by 18PatZ** [comment]
Yep, I was able to reproduce it too. The root issue is that when loading the data, it's attempting to set the blocks broken into a list at certain indices instead of appending them, requiring a pre-allocated list made by addEmptiesFor. The stage number for this was hardcoded to be the first stage only, so any stages past that will lose their data. I'm pushing a simple fix for this.

**Comment by Nericu** [comment]
Awesome glad this has been figured out. Would either one of you be able to also check the smelting quest. I submitted an issue with it just not tracking at all awhile back and think it might also be because its a stage 2 quest as well.

**Comment by 18PatZ** [comment]
@Nericu the only quests that should have been affected by this bug are blocks broken, placed, damaged, used, and cut. Your smelting quest worked fine for me, both with and without the fix - if there's an issue with it then it's a different bug.

**Comment by Nericu** [comment]
Ok no worries just figured I would check thanks
