### ISSUE TITLE
Quests disappears when player quit on the server

### ISSUE THREAD

**Issue by CrashyTop** [PikaMug/Quests#890]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.7
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I have an issue on my server with the Quests plugin, when players claim a new quest using the command or even the NPC, for example, the quest is, "Mine 50 Blocks" and he start to mine his blocks, but when he log out and come back to the server his quests resets completely, seems that he don't even have the quest enabled.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
This has already been resolved as of Quests 3.7.8

**Comment by CrashyTop** [comment]
I updated and I still have this saving issue, the player leaves and resets the quest

**Comment by PikaMug** [comment]
@CrashyTop Please provide a quests.yml for testing

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CrashyTop** [comment]
@PikaMug https://pastebin.com/7mCWD5eC

**Comment by PikaMug** [comment]
@CrashyTop Thanks. I don't see any quests in that file for mining 50 blocks. Which quest are you using to produce this?

**Comment by CrashyTop** [comment]
I cited as an example, all quests when the player leaves the server and comes back resets. I created 3 Daily, Weekly and Monthly stocks. That is, he can leave the server and come back and continue counting a mission.

**Comment by PikaMug** [comment]
Alright. I wasn't able to replicate this using your "Minerador 1 - Diaria" quest. I took the quest and broke 3 lapis ore, then relogged and the plugin still showed that I had broken 3 ore. Even after restarting the server, it _still_ showed 3 ore:

![relog](https://user-images.githubusercontent.com/2267126/62592371-fbc85880-b8a0-11e9-9b02-664d78487422.png)

The behavior you described was fixed in #793 for Quests 3.7.8. Are you 100% sure you haven't re-installed an older version by accident?

**Comment by CrashyTop** [comment]
yes I have. I downloaded the last one, checked. But, I don't know why it resets. I created actions can be that?
Version my server is 1.8.8

**Comment by CrashyTop** [comment]
Not saving so much that resets even the quest leaderheads

**Comment by CrashyTop** [comment]
I managed to solve.
It was the actions with timer, but it was not necessary to put because it had cooldown.

**Comment by PikaMug** [comment]
@CrashyTop Glad you found the problem. I’ll look into what could be wrong with the timer.
