### ISSUE TITLE
Denizen Scripts fire one step in advance.

### ISSUE THREAD

**Issue by MooshroomStatus** [PikaMug/Quests#941]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests Version: 3.7.8-b16

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Create a quest involving multiple steps. an easy quick way would be just doing reach locations (though anything works). Add a denizen script to be performed on each step. The second script will run in place of the first, third in place of the second, etc. Each script I used in the quest is a task script that uses CHAT scripting, so nothing complex. 

EDIT: After testing, I realize that the last script also fires twice, both before you start the last step and after you complete it.

ANOTHER EDIT: Turns out scripts don't properly fire at any point and just kinda activate whenever they want to. I have another quest that runs scripts. At some parts, the scripts run early, at others, they dont get run at all. Here's what I got so far.

1- Step 1 runs step 2's script
2- Step 2 doesn't run step 2's script
3- Step 3 doesn't have a script (Didnt add one for this step)
4- Step 4 runs step 5's script.
5- Step 5 runs Completion script
Completion - runs Completion script

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/vXevqsKp

**Comment by PikaMug** [comment]
Thanks for your report. I believe this has already been resolved in the 3.8.0 dev builds. Please give the a latest a try, or wait until the official release. Once you've tried it, feel free to comment if the ticket should be reopened.

https://ci.codemc.org/job/PikaMug/job/Quests/

**Comment by MooshroomStatus** [comment]
This problem still persists in version 3.8.0. I updated the quest to run the scripts in the order theyre meant to be run and they still run 1 script in advance.

**Comment by PikaMug** [comment]
Related to #931 but not technically a duplicate

Fix available in https://ci.codemc.org/job/PikaMug/job/Quests/32/
