### ISSUE TITLE
Potion-function on items is not working

### ISSUE THREAD

**Issue by Sponge1996** [PikaMug/Quests#952]
**What is your Quests version / build number (do _not_ say "latest")?**

Quests-Version: 3.7.8
Minecraft-Server-Version: 1.14.4

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

If I enter several brewing recipes only the name POTION is displayed. Example: Potion for bounce and Potion for night vision is only one thing possible when brewing and other brewing recipes are no longer recognized

No matter which potion you take into the inventory after the brews, the first potion is completed and no other potion is recognized afterwards.

i have no errors in the console

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

https://pastebin.com/3UJ6viNG

![Potion_in_items](https://user-images.githubusercontent.com/18584669/66268755-e8098600-e840-11e9-96a2-d937dad3aa2e.png)

![Quest ingame](https://user-images.githubusercontent.com/18584669/66268802-52222b00-e841-11e9-88b7-84d53e78b39e.png)

![Potion_brew](https://user-images.githubusercontent.com/18584669/66268758-e8a21c80-e840-11e9-9afb-2902bd41c345.png)

![potion_complete](https://user-images.githubusercontent.com/18584669/66268754-e770ef80-e840-11e9-9cf9-2e31681a252b.png)

![Potion_2](https://user-images.githubusercontent.com/18584669/66268757-e8098600-e840-11e9-8989-9985f370d632.png)

![potion_quest_2](https://user-images.githubusercontent.com/18584669/66268756-e8098600-e840-11e9-8de4-5af7f97534d2.png)

**Comment by PikaMug** [comment]
Already resolved in latest development builds. Feel free to give them a try at:
https://ci.codemc.io/job/PikaMug/job/Quests/

Note that you will likely have to edit your quest and update the rewards for changes to take effect.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sponge1996** [comment]
With the last Dev Update 3.8.0 the problem is still there, I have installed the plugin completely and still only the first randompotion is accepted and no others afterwards. Do you have a solution ? i have the same problems in the version 3.8.0 on the Minecraftserver version 1.14.4

**Comment by PikaMug** [comment]
Did you update your reward in the editor like I mentioned? The quest needs to be re-saved.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sponge1996** [comment]
I completely reinstalled the plugin and did the Quest again, which unfortunately had the same effect as the last version. Also some potions are displayed with the Potion Meta ID instead of the name. If you like I can also show you from the quest create it

**Comment by PikaMug** [comment]
I was able to replicate the issue you're describing. Working on a solution now.

**Comment by PikaMug** [comment]
Thanks for your patience. Please give the following build a try, once available:
https://ci.codemc.io/job/PikaMug/job/Quests/34/
